version: "3"
services:
  nest-app:
    build: .
    ports:
    - "3000:3000"
    volumes:
      ./mountedNest:/app
    environment:
      - PORT=3000
      - NODE_ENV=production
    command: node dist/main

